version: '3.8'

networks:
  aiops:
    driver: bridge
  web:
    driver: bridge
  internal:
    driver: bridge

services:
  ############################################
  # TRAEFIK (reverse proxy)
  ############################################
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Use local CA cert
      - "--tls.certificates[0].certFile=/certs/pristine-aiops.crt"
      - "--tls.certificates[0].keyFile=/certs/pristine-aiops.key"
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
    networks:
      - aiops 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.pristine-aiops.local`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

  ############################################
  # FASTAPI BACKEND
  ############################################
  backend:
    #container_name: fastapi
    image: ghcr.io/rberbatovci/backend:latest 
    expose:
      - "8000"
    networks:
      - aiops
    depends_on:
      postgresql:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - shared-mibs:/app/traps/producer/mibs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`app.pristine-aiops.local`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    extra_hosts:
      - "auth.pristine-aiops.local:host-gateway"

  ############################################
  # FRONTEND (REACT SERVED BY NGINX)
  ############################################
  frontend:
    container_name: react
    image: ghcr.io/rberbatovci/backend:latest 
    depends_on:
      - backend
      - keycloak
      - opensearch-node1
    networks:
      - aiops
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.pristine-aiops.local`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  ############################################
  # KEYCLOAK
  ############################################
  keycloak:
    container_name: keycloak
    image: ghcr.io/rberbatovci/keycloak:latest  
    command:
      - start
      - --import-realm
      - --hostname=auth.pristine-aiops.local
      - --http-relative-path=/auth
      - --http-port=8080
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - postgresql
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Admin123!
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - aiops
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.pristine-aiops.local`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  ############################################
  # OPENLDAP
  ############################################
  #openldap:
  #  image: osixia/openldap:1.5.0
  #  container_name: openldap
  #  environment:
  #    LDAP_ORGANISATION: "Pristine AIOps"
  #    LDAP_DOMAIN: "pristine.local"
  #    LDAP_ADMIN_PASSWORD: "admin"
  #  networks:
  #    - aiops
  #  restart: unless-stopped


  ############################################
  # PHP LDAP Admin
  ############################################
  #phpldapadmin:
  #  image: osixia/phpldapadmin:0.9.0
  #  container_name: phpldapadmin
  #  environment:
  #    PHPLDAPADMIN_LDAP_HOSTS: openldap
  #    PHPLDAPADMIN_HTTPS: "false"
  #  networks:
  #    - aiops
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.ldapui.rule=Host(`ldap.pristine-aiops.local`)"
  #    - "traefik.http.routers.ldapui.entrypoints=websecure"
  #    - "traefik.http.routers.ldapui.tls=true"
  #    - "traefik.http.services.ldapui.loadbalancer.server.port=80"

  ############################################
  # FREERADIUS
  ############################################
  #freeradius:
  #  build:
  #    context: .
  #    dockerfile: ./dockerfiles/Dockerfile.freeradius
  #  container_name: FreeRADIUS
  #  ports:
  #      - "1812:18120/udp"
  #      - "1813:18130/udp"
  #  depends_on:
  #    - keycloak
  #    - openldap
  #  networks:
  #    - aiops
  #  volumes:
  #    - /etc/ssl/certs/win-server01.pristine-aiops.local.pem:/etc/ssl/certs/win-server01.pristine-aiops.local.pem:ro
  #  labels:
  #    - "traefik.enable=false"
  #  extra_hosts:
  #    - "WinServer01.pristine-aiops.local:192.168.1.202"
  #  restart: unless-stopped

  postgresql:
    container_name: PostgreSQL 
    image: ghcr.io/rberbatovci/postgresql:latest 
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aiops

  kafka:
    container_name: Kafka
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
      KAFKA_CREATE_TOPICS: "unknown:1:1,topology-topic:1:1,telemetry-signals:1:1,cpu-utilization:1:1,memory-statistics:1:1,interface-statistics:1:1,interface-oper-status:1:1,bgp-connections:1:1,isis-statistics:1:1,syslog-events:1:1,trap-events:1:1,netflow-events:1:1,syslog-signals:1:1,trap-signals:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 50
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9093 --list > /dev/null 2>&1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - aiops

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc 127.0.0.1 2181 | grep Mode"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s
    networks:
      - aiops
      
  ############################################
  # OPENSEARCH + DASHBOARDS
  ############################################
  opensearch:
    image: opensearchproject/opensearch-dashboards:3.1.0
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200","http://opensearch-node2:9200","http://opensearch-node3:9200"]'
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    depends_on: 
      - opensearch-node1
      - opensearch-node2
      - opensearch-node3
    ports:
      - "5601:5601"
    networks:
      - aiops
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.opensearch.rule=Host(`opensearch.pristine-aiops.local`)"
    - "traefik.http.routers.opensearch.entrypoints=websecure"
    - "traefik.http.routers.opensearch.tls=true"
    - "traefik.http.services.opensearch.loadbalancer.server.port=5601"

  opensearch-node1:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - aiops

  opensearch-node2:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - aiops

  opensearch-node3:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-node3
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - aiops

  redis:
    container_name: Redis
    image: redis:latest
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data
    networks:
      - aiops 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
 

  syslog-producer:
    container_name: SyslogProducer
    image: ghcr.io/rberbatovci/syslog-producer:latest 
    environment:
      SYSLOG_PORT: ${SYSLOG_PORT:-1160}
    env_file:
      - .env
    ports:
      - "${SYSLOG_PORT}:${SYSLOG_PORT}/udp"
    depends_on:
      kafka:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  syslog-consumer:
    container_name: SyslogConsumer
    image: ghcr.io/rberbatovci/syslog-consumer:latest 
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    labels: 
      - "traefik.enable=false"
    networks:
      - aiops
    restart: unless-stopped

  syslog-signals:
    container_name: SyslogSignals
    image: ghcr.io/rberbatovci/syslog-signals:latest 
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    networks:
      - aiops
    restart: unless-stopped

  trap-signals:
    container_name: TrapSignals
    image: ghcr.io/rberbatovci/trap-signals:latest 
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    networks:
      - aiops
    restart: unless-stopped

  #poll-producer:
  #  container_name: PollProducer
    #image: ghcr.io/rberbatovci/poll-producer:latest
  #  build:
  #    context: .
  #    dockerfile: ./dockerfiles/Dockerfile.poll-producer
  #  env_file:
  #    - .env
  #  ports:
  #    - "1161:1161/udp"
  #  volumes:
  #    - shared-mibs:/app/traps/producer/mibs
  #  depends_on:
  #    kafka:
  #      condition: service_healthy
  #  labels:
  #    - "traefik.enable=false"
  #  networks:
  #    - aiops

  trap-producer:
    container_name: TrapProducer
    image: ghcr.io/rberbatovci/trap-producer:latest 
    environment:
      SNMP_AUTH_PASS: ${SNMP_AUTH_PASS}
      SNMP_PRIV_PASS: ${SNMP_PRIV_PASS}
      SNMP_USERNAME: ${SNMP_USERNAME}
      SNMP_ENGINE_ID: ${SNMP_ENGINE_ID}
      SNMP_TRAP_PORT: ${SNMP_TRAP_PORT}
    env_file:
      - .env
    ports:
      - "1161:1161/udp"
    volumes:
      - shared-mibs:/app/traps/producer/mibs
    depends_on:
      kafka:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  trap-consumer:
    container_name: TrapConsumer
    image: ghcr.io/rberbatovci/trap-consumer:latest 
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    networks:
      - aiops
    restart: unless-stopped

  netflow-producer:
    container_name: NetflowProducer
    image: ghcr.io/rberbatovci/netflow-producer:latest 
    ports:
      - "1162:1162/udp"
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    labels:
     - "traefik.enable=false"
    networks:
      - aiops

  netflow-consumer:
    container_name: NetflowConsumer
    image: ghcr.io/rberbatovci/netflow-consumer:latest 
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  gobgp:
    container_name: GoBGP
    image: ghcr.io/rberbatovci/gobgp-server:latest
    env_file:
      - .env
    ports:
      - "179:179"
      - "50051:50051"
    labels:
      - "traefik.enable=false"
    networks:
      - aiops
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=gobgp:50051"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  telemetry-producer:
    container_name: TelemetryProducer
    image: ghcr.io/rberbatovci/telemetry-producer:latest 
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=telemetry-topic
    ports:
      - "1163:1163"
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  cpu-util-stats:
    container_name: CPUUtilStatistics
    image: ghcr.io/rberbatovci/telemetry-cpu-util-stats:latest 
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  memory-statistics:
    container_name: MemoryStatistics
    image: ghcr.io/rberbatovci/telemetry-memory-stats:latest 
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - aiops
      
  interface-oper-status:
    container_name: InterfaceOperStatus
    image: ghcr.io/rberbatovci/telemetry-interface-oper-status:latest 
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  interface-statistics:
    container_name: InterfaceStatistics
    image: ghcr.io/rberbatovci/telemetry-interface-stats:latest 
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - aiops

  bgp-connection-statistics:
    container_name: BGPConnectionStatistics
    image: ghcr.io/rberbatovci/telemetry-interface-stats:latest 
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
    networks:
      - aiops
  
volumes:
  postgres_data:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:
  shared-mibs:
  keycloak-db:
