version: '3.8'

networks:
  aiops:
    driver: bridge

services:
  backend:
    container_name: FastAPI
    image: ghcr.io/rberbatovci/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - shared-mibs:/app/traps/producer/mibs
    networks:
      - aiops
    entrypoint: ["/app/entrypoint.sh"]

  frontend:
    container_name: ReactJS
    image: ghcr.io/rberbatovci/frontend:latest
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - aiops

  postgresql:
    image: ghcr.io/rberbatovci/postgresql:latest
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aiops

  kafka:
    container_name: Kafka
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "telemetry-signals:1:1,cpu-utilization:1:1,memory-statistics:1:1,interface-statistics:1:1,bgp-connections:1:1,isis-statistics:1:1,syslog-events:1:1,trap-events:1:1,netflow-events:1:1,syslog-signals:1:1,trap-signals:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 50
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_started
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiops

  zookeeper:
    container_name: Zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiops

  opensearch-node1:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"   # REST API
      - "9600:9600"   # Performance Analyzer
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - aiops

  opensearch-node2:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - aiops

  opensearch-node3:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-node3
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - aiops

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200","https://opensearch-node3:9200"]'
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      OPENSEARCH_SSL_VERIFICATIONMODE: none
    depends_on: 
      - opensearch-node1
      - opensearch-node2
      - opensearch-node3
    ports:
      - "5601:5601"
    networks:
      - aiops

  syslog-producer:
    container_name: SyslogProducer
    image: ghcr.io/rberbatovci/syslog-producer:latest
    env_file: .env
    ports:
      - "1160:1160/udp"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aiops

  syslog-consumer:
    container_name: SyslogConsumer
    image: ghcr.io/rberbatovci/syslog-consumer:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    networks:
      - aiops
    restart: unless-stopped

  syslog-signals:
    container_name: SyslogSignals
    image: ghcr.io/rberbatovci/syslog-signals:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aiops
    restart: unless-stopped

  trap-signals:
    container_name: TrapSignals
    image: ghcr.io/rberbatovci/traps-signals:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aiops
    restart: unless-stopped

  trap-producer:
    container_name: TrapProducer
    image: ghcr.io/rberbatovci/traps-producer:latest
    env_file: .env
    ports:
      - "1161:1161/udp"
    volumes:
      - shared-mibs:/app/traps/producer/mibs
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aiops

  trap-consumer:
    container_name: TrapConsumer
    image: ghcr.io/rberbatovci/traps-consumer:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aiops
    restart: unless-stopped

  netflow-producer:
    container_name: NetflowProducer
    image: ghcr.io/rberbatovci/netflow-producer:latest
    ports:
      - "1162:1162/udp"
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aiops

  netflow-consumer:
    container_name: NetflowConsumer
    image: ghcr.io/rberbatovci/netflow-consumer:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aiops

  telemetry-producer:
    container_name: TelemetryProducer
    image: ghcr.io/rberbatovci/telemetry-producer:latest
    env_file: .env
    ports:
      - "1163:1163"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - aiops

  cpu-util-stats:
    container_name: CPUUtilStatistics
    image: ghcr.io/rberbatovci/telemetry-cpu-util-stats:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aiops

  memory-statistics:
    container_name: MemoryStatistics
    image: ghcr.io/rberbatovci/telemetry-memory-stats:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aiops
      
  interface-statistics:
    container_name: InterfaceStatistics
    image: ghcr.io/rberbatovci/telemetry-interface-stats:latest
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aiops
  
volumes:
  postgres_data:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:
  shared-mibs:
